### ISSUE TITLE
NodeJS backend not rendering themes to SVG

### ISSUE THREAD

**Issue by versipellis** [altair-viz/altair_saver#98] opened 2021-11-08 22:55 UTC
Possibly related to #21 #22 and #81 - but the nodeJS backend is not properly rendering themes applied to SVG outputs, both when using chart.save('output.svg')`, `chart.save('output.svg', embed_options={'renderer':'svg'})`, and `save(chart, "output.svg")`. It renders fine in Jupyter and vega-embed.

**Comment by jakevdp** [comment] 2021-11-08 23:23
Thanks - I believe this is a duplicate of #81. vega-cli (used by nodejs) does not support themes. There is a workaround linked in that issue.

**Comment by versipellis** [comment] 2021-11-15 03:46
Ah, I misread that issue. Thanks @jakevdp - with both the Selenium renderer and vega-cli installed, how does one specify which renderer to use?

**Closed** 2021-11-16 07:31 UTC
